version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    networks:
      - app_network
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app_network
  nginx:
    image: nginx:alpine
    networks:
      - app_network
  front:
    build: ../front
    extra_hosts:
     - 'host.docker.internal:host-gateway'
    volumes:
      - ../front:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge
